version: "2"

networks:
  httypist:
    external: false

services:
  httypist:
    container_name: httypist
    image: my_registry/httypist:latest
    environment:
      - REDIS_URL=redis://httypist_redis
      - GIT_URL=git@github.como:my/repo
    restart: always
    ports:
      - "127.0.0.1:8555:8000"
    networks:
      - httypist
    volumes:
      - /var/docker/httypist/app:/app
      # Place a proper passwordless ssh key for accessing the repo under GIT_URL in /app/ssh_key_for_repo
  redis:
    container_name: httypist_redis
    image: redis
    restart: always
    networks:
      - httypist
  httypist-processor:
    environment:
      - REDIS_URL=redis://httypist_redis
    container_name: httypist_processor
    #example
    image: my_registry/httypist-processor:latest
    restart: always
    volumes_from:
      - httypist
    networks:
      - httypist
